/*
Copyright 2008 WebAtlas
Authors : Mathieu Bastian, Mathieu Jacomy, Julian Bilcke
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.gephi.timeline.ui;

import java.io.Serializable;
import java.util.logging.Logger;
import org.gephi.timeline.api.TimelineDataModel;
import org.gephi.timeline.ui.layers.impl.UpperPaneBackgroundLayer;
import org.gephi.timeline.ui.layers.impl.UpperPaneDataLayer;
import org.gephi.timeline.ui.skins.api.TimelineSkin;
import org.gephi.timeline.ui.skins.impl.DefaultSkin;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class TimelineTopComponent extends TopComponent {

    private static TimelineTopComponent instance;

    private TimelineSkin skin = new DefaultSkin();
    private TimelineDataModel model = new FakeTimelineDataModel();

    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "resources/date.png";

    private static final String PREFERRED_ID = "TimelineTopComponent";
    private static final long serialVersionUID = 1L;

    private TimelineTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TimelineTopComponent.class, "CTL_TimelineTopComponent"));
        setToolTipText(NbBundle.getMessage(TimelineTopComponent.class, "HINT_TimelineTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperBackground = new UpperPaneBackgroundLayer();
        upperData = new UpperPaneDataLayer();
        bottomBackground = new org.gephi.timeline.ui.layers.impl.BottomPaneBackgroundLayer();
        bottomData = new org.gephi.timeline.ui.layers.impl.BottomPaneDataLayer();

        upperBackground.setBorder(null);

        upperData.setBorder(null);
        upperData.setModel(model);
        upperData.setSkin(skin);
        upperData.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                upperDataMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout upperDataLayout = new javax.swing.GroupLayout(upperData);
        upperData.setLayout(upperDataLayout);
        upperDataLayout.setHorizontalGroup(
            upperDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        upperDataLayout.setVerticalGroup(
            upperDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout upperBackgroundLayout = new javax.swing.GroupLayout(upperBackground);
        upperBackground.setLayout(upperBackgroundLayout);
        upperBackgroundLayout.setHorizontalGroup(
            upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        upperBackgroundLayout.setVerticalGroup(
            upperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bottomBackground.setBorder(null);

        bottomData.setBorder(null);
        bottomData.setModel(model);
        bottomData.setSkin(skin);

        javax.swing.GroupLayout bottomDataLayout = new javax.swing.GroupLayout(bottomData);
        bottomData.setLayout(bottomDataLayout);
        bottomDataLayout.setHorizontalGroup(
            bottomDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        bottomDataLayout.setVerticalGroup(
            bottomDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bottomBackgroundLayout = new javax.swing.GroupLayout(bottomBackground);
        bottomBackground.setLayout(bottomBackgroundLayout);
        bottomBackgroundLayout.setHorizontalGroup(
            bottomBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bottomBackgroundLayout.setVerticalGroup(
            bottomBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(upperBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upperDataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upperDataMouseMoved
        // TODO add your handling code here:
}//GEN-LAST:event_upperDataMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gephi.timeline.ui.layers.impl.BottomPaneBackgroundLayer bottomBackground;
    private org.gephi.timeline.ui.layers.impl.BottomPaneDataLayer bottomData;
    private org.gephi.timeline.ui.layers.impl.UpperPaneBackgroundLayer upperBackground;
    private org.gephi.timeline.ui.layers.impl.UpperPaneDataLayer upperData;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized TimelineTopComponent getDefault() {
        if (instance == null) {
            instance = new TimelineTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the TimelineTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized TimelineTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(TimelineTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof TimelineTopComponent) {
            return (TimelineTopComponent) win;
        }
        Logger.getLogger(TimelineTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return TimelineTopComponent.getDefault();
        }
    }
}
