/*
Copyright 2008-2010 Gephi
Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
Website : http://www.gephi.org

This file is part of Gephi.

DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

Copyright 2011 Gephi Consortium. All rights reserved.

The contents of this file are subject to the terms of either the GNU
General Public License Version 3 only ("GPL") or the Common
Development and Distribution License("CDDL") (collectively, the
"License"). You may not use this file except in compliance with the
License. You can obtain a copy of the License at
http://gephi.org/about/legal/license-notice/
or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
specific language governing permissions and limitations under the
License.  When distributing the software, include this License Header
Notice in each file and include the License files at
/cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
License Header, with the fields enclosed by brackets [] replaced by
your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

If you wish your version of this file to be governed by only the CDDL
or only the GPL Version 3, indicate your decision by adding
"[Contributor] elects to include this software in this distribution
under the [CDDL or GPL Version 3] license." If you do not indicate a
single choice of license, a recipient has the option to distribute
your version of this file under either the CDDL, the GPL Version 3 or
to extend the choice of license to its licensees as provided above.
However, if you add GPL Version 3 code and therefore, elected the GPL
Version 3 license, then the option applies only if the new code is
made subject to such option by the copyright holder.

Contributor(s):

Portions Copyrighted 2011 Gephi Consortium.
 */

package org.gephi.ui.filters.plugin.graph;

import org.gephi.filters.plugin.graph.ShortestPathBuilder.ShortestPathFilter;

/**
 * @author Mathieu Bastian
 */
public class ShortestPathPanel extends javax.swing.JPanel {

    private ShortestPathFilter shortestPathFilter;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNodeId1;
    private javax.swing.JLabel labelNodeId2;
    private javax.swing.JTextField nodeIdTextField;
    private javax.swing.JTextField nodeIdTextField2;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form EgoPanel
     */
    public ShortestPathPanel() {
        initComponents();

        okButton1.addActionListener(e -> shortestPathFilter.getProperties()[0].setValue(nodeIdTextField.getText()));

        okButton2.addActionListener(e -> shortestPathFilter.getProperties()[1].setValue(nodeIdTextField2.getText()));
    }

    public void setup(ShortestPathFilter shortestPathFilter) {
        this.shortestPathFilter = shortestPathFilter;
        nodeIdTextField.setText(shortestPathFilter.getFirstNodePattern());
        nodeIdTextField2.setText(shortestPathFilter.getSecondNodePattern());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNodeId1 = new javax.swing.JLabel();
        nodeIdTextField = new javax.swing.JTextField();
        okButton1 = new javax.swing.JButton();
        labelNodeId2 = new javax.swing.JLabel();
        nodeIdTextField2 = new javax.swing.JTextField();
        okButton2 = new javax.swing.JButton();

        labelNodeId1.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.labelNodeId1.text")); // NOI18N

        nodeIdTextField.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.nodeIdTextField.text")); // NOI18N
        nodeIdTextField.setToolTipText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.nodeIdTextField.toolTipText")); // NOI18N

        okButton1.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.okButton1.text")); // NOI18N
        okButton1.setMargin(new java.awt.Insets(2, 7, 2, 7));

        labelNodeId2.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.labelNodeId2.text")); // NOI18N

        nodeIdTextField2.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.nodeIdTextField2.text")); // NOI18N
        nodeIdTextField2.setToolTipText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.nodeIdTextField2.toolTipText")); // NOI18N

        okButton2.setText(org.openide.util.NbBundle.getMessage(ShortestPathPanel.class,
            "ShortestPathPanel.okButton2.text")); // NOI18N
        okButton2.setMargin(new java.awt.Insets(2, 7, 2, 7));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNodeId1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nodeIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNodeId2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nodeIdTextField2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(okButton1)
                        .addComponent(okButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNodeId1)
                        .addComponent(nodeIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(okButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNodeId2)
                        .addComponent(nodeIdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(okButton2))
                    .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
}
