/*
Copyright 2008-2010 Gephi
Authors : Eduardo Ramos <eduramiba@gmail.com>
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gephi.datalaboratory.impl.utils;

import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;


/**
 * Simple class to show a dialog with a report with some html and some window title.
 * TODO: Maybe make StatisticsReportPanel a reusable UI util?
 * @author Eduardo Ramos <eduramiba@gmail.com>
 */
public class SimpleHTMLReport extends javax.swing.JPanel {

    /** Creates new form ColumnValuesFrequencyUI */
    public SimpleHTMLReport(String title, String html) {
        initComponents();

        reportText.setContentType("text/html;");
        reportText.setText(html);

        DialogDescriptor dd = new DialogDescriptor(this, title);
        dd.setModal(false);
        dd.setOptions(new Object[]{NbBundle.getMessage(SimpleHTMLReport.class, "SimpleHTMLReport.option.close")});
        DialogDisplayer.getDefault().notify(dd);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        reportText = new javax.swing.JEditorPane();

        reportText.setEditable(false);
        scroll.setViewportView(reportText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane reportText;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
