/*
 Copyright 2008-2010 Gephi
 Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
 Website : http://www.gephi.org

 This file is part of Gephi.

 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

 Copyright 2011 Gephi Consortium. All rights reserved.

 The contents of this file are subject to the terms of either the GNU
 General Public License Version 3 only ("GPL") or the Common
 Development and Distribution License("CDDL") (collectively, the
 "License"). You may not use this file except in compliance with the
 License. You can obtain a copy of the License at
 http://gephi.org/about/legal/license-notice/
 or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
 specific language governing permissions and limitations under the
 License.  When distributing the software, include this License Header
 Notice in each file and include the License files at
 /cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
 License Header, with the fields enclosed by brackets [] replaced by
 your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"

 If you wish your version of this file to be governed by only the CDDL
 or only the GPL Version 3, indicate your decision by adding
 "[Contributor] elects to include this software in this distribution
 under the [CDDL or GPL Version 3] license." If you do not indicate a
 single choice of license, a recipient has the option to distribute
 your version of this file under either the CDDL, the GPL Version 3 or
 to extend the choice of license to its licensees as provided above.
 However, if you add GPL Version 3 code and therefore, elected the GPL
 Version 3 license, then the option applies only if the new code is
 made subject to such option by the copyright holder.

 Contributor(s):

 Portions Copyrighted 2011 Gephi Consortium.
 */

package org.gephi.ui.tools.plugin;

import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.function.BiConsumer;
import java.util.function.Function;
import org.gephi.graph.api.Graph;
import org.gephi.graph.api.GraphController;
import org.gephi.graph.api.GraphModel;
import org.gephi.graph.api.Node;
import org.openide.util.Lookup;

/**
 * @author Mathieu Bastian
 */
public class TransformPanel extends javax.swing.JPanel {

    private float avgSize;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton horizontalSymBtn;
    private javax.swing.JButton verticalSymBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form SizePanel
     */
    public TransformPanel() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verticalSymBtn = new javax.swing.JButton();
        horizontalSymBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        verticalSymBtn.setText(org.openide.util.NbBundle.getMessage(TransformPanel.class, "TransformPanel.verticalSymBtn.text")); // NOI18N
        verticalSymBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalSymBtnActionPerformed(evt);
            }
        });
        add(verticalSymBtn, new java.awt.GridBagConstraints());

        horizontalSymBtn.setText(org.openide.util.NbBundle.getMessage(TransformPanel.class, "TransformPanel.horizontalSymBtn.text")); // NOI18N
        horizontalSymBtn.setActionCommand(org.openide.util.NbBundle.getMessage(TransformPanel.class, "TransformPanel.horizontalSymBtn.actionCommand")); // NOI18N
        horizontalSymBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalSymBtnActionPerformed(evt);
            }
        });
        add(horizontalSymBtn, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void symetricalProcess(Function<Node, Float> nodeGetFunction,BiConsumer<Node, Float> nodeSetFunction)  {

        GraphController graphController = Lookup.getDefault().lookup(GraphController.class);

        GraphModel graphModel = graphController.getGraphModel();
        Graph graph = graphModel.getGraphVisible();
        graph.writeLock();
        try {
            final float barycenter = Arrays.stream(graph.getNodes().toArray())
                .parallel()
                .map(nodeGetFunction)
                .reduce(0.f,Float::sum) / graph.getNodeCount();


            Arrays.stream(graph.getNodes().toArray()).parallel().forEach( node -> {
                if (node.isFixed()) return;
                float delta = (nodeGetFunction.apply(node) - barycenter) * -1;
                nodeSetFunction.accept(node,barycenter + delta);
            });
        } finally {
            graph.writeUnlock();
        }
    }
    private void verticalSymBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalSymBtnActionPerformed
        symetricalProcess(Node::x,Node::setX);
    }//GEN-LAST:event_verticalSymBtnActionPerformed

    private void horizontalSymBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalSymBtnActionPerformed
        symetricalProcess(Node::y,Node::setY);
    }//GEN-LAST:event_horizontalSymBtnActionPerformed
}
