/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModularityPanel.java
 *
 * Created on Jul 7, 2009, 3:24:07 AM
 */

package org.gephi.statistics.ui;

import javax.swing.JPanel;
import org.gephi.statistics.Modularity;
import org.gephi.statistics.api.Statistics;
import org.gephi.statistics.ui.api.StatisticsUI;

/**
 *
 * @author pjmcswee
 */
public class ModularityPanel extends javax.swing.JPanel {

    /** Creates new form ModularityPanel */
    public ModularityPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        randomButton = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ModularityPanel.class, "ModularityPanel.jLabel1.text")); // NOI18N

        randomButton.setText(org.openide.util.NbBundle.getMessage(ModularityPanel.class, "ModularityPanel.randomButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(randomButton)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(randomButton)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JRadioButton randomButton;
    // End of variables declaration//GEN-END:variables
 /**
     *
     */
    public static class ModularityUI implements StatisticsUI {

        private ModularityPanel panel;
        private Modularity mod;

        /**
         * 
         */
        public ModularityUI() {
            panel = new ModularityPanel();
        }

        /**
         *
         */
        public void unsetup() {
            //Set params
            try {
                boolean doRandom = panel.randomButton.isSelected();
                mod.setRandom(doRandom);
            } catch (Exception e) {
            }
        }

       
        /**
         *
         * @param statistics
         */
        public void setup(Statistics statistics) {
            this.mod = (Modularity) statistics;
           
            panel.randomButton.setSelected(mod.getRandom());
        }

        /**
         * 
         * @return
         */
        public JPanel getPanel() {
            return panel;
        }
    }

}
