/*
Copyright 2008-2010 Gephi
Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
Website : http://www.gephi.org

This file is part of Gephi.

DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

Copyright 2011 Gephi Consortium. All rights reserved.

The contents of this file are subject to the terms of either the GNU
General Public License Version 3 only ("GPL") or the Common
Development and Distribution License("CDDL") (collectively, the
"License"). You may not use this file except in compliance with the
License. You can obtain a copy of the License at
http://gephi.org/about/legal/license-notice/
or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
specific language governing permissions and limitations under the
License.  When distributing the software, include this License Header
Notice in each file and include the License files at
/cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
License Header, with the fields enclosed by brackets [] replaced by
your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

If you wish your version of this file to be governed by only the CDDL
or only the GPL Version 3, indicate your decision by adding
"[Contributor] elects to include this software in this distribution
under the [CDDL or GPL Version 3] license." If you do not indicate a
single choice of license, a recipient has the option to distribute
your version of this file under either the CDDL, the GPL Version 3 or
to extend the choice of license to its licensees as provided above.
However, if you add GPL Version 3 code and therefore, elected the GPL
Version 3 license, then the option applies only if the new code is
made subject to such option by the copyright holder.

Contributor(s):

Portions Copyrighted 2011 Gephi Consortium.
*/

package org.gephi.desktop.io.export;

/**
 *
 * @author Mathieu Bastian
 */
public class GraphFileExporterUIPanel extends javax.swing.JPanel {

    /** Creates new form GraphFileExporterUIPanel */
    public GraphFileExporterUIPanel() {
        initComponents();
    }

    public void setVisibleOnlyGraph(boolean value) {
        graphButtonGroup.setSelected((value?visibleOnlyRadio.getModel():fullGraphRadio.getModel()), true);
    }

    public boolean isVisibleOnlyGraph() {
        return graphButtonGroup.isSelected(visibleOnlyRadio.getModel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphButtonGroup = new javax.swing.ButtonGroup();
        labelGraph = new javax.swing.JLabel();
        fullGraphRadio = new javax.swing.JRadioButton();
        visibleOnlyRadio = new javax.swing.JRadioButton();
        labelFullgraph = new javax.swing.JLabel();
        labelVisibleOnly = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelGraph.setText(org.openide.util.NbBundle.getMessage(GraphFileExporterUIPanel.class, "GraphFileExporterUIPanel.labelGraph.text")); // NOI18N

        graphButtonGroup.add(fullGraphRadio);
        fullGraphRadio.setSelected(true);
        fullGraphRadio.setText(org.openide.util.NbBundle.getMessage(GraphFileExporterUIPanel.class, "GraphFileExporterUIPanel.fullGraphRadio.text")); // NOI18N

        graphButtonGroup.add(visibleOnlyRadio);
        visibleOnlyRadio.setText(org.openide.util.NbBundle.getMessage(GraphFileExporterUIPanel.class, "GraphFileExporterUIPanel.visibleOnlyRadio.text")); // NOI18N

        labelFullgraph.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelFullgraph.setForeground(new java.awt.Color(102, 102, 102));
        labelFullgraph.setText(org.openide.util.NbBundle.getMessage(GraphFileExporterUIPanel.class, "GraphFileExporterUIPanel.labelFullgraph.text")); // NOI18N

        labelVisibleOnly.setFont(new java.awt.Font("Tahoma", 0, 10));
        labelVisibleOnly.setForeground(new java.awt.Color(102, 102, 102));
        labelVisibleOnly.setText(org.openide.util.NbBundle.getMessage(GraphFileExporterUIPanel.class, "GraphFileExporterUIPanel.labelVisibleOnly.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGraph)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visibleOnlyRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelVisibleOnly))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fullGraphRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFullgraph)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGraph)
                    .addComponent(fullGraphRadio)
                    .addComponent(labelFullgraph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visibleOnlyRadio)
                    .addComponent(labelVisibleOnly))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton fullGraphRadio;
    private javax.swing.ButtonGroup graphButtonGroup;
    private javax.swing.JLabel labelFullgraph;
    private javax.swing.JLabel labelGraph;
    private javax.swing.JLabel labelVisibleOnly;
    private javax.swing.JRadioButton visibleOnlyRadio;
    // End of variables declaration//GEN-END:variables

}
