/*
Copyright 2008-2010 Gephi
Authors : Jeremy Subtil <jeremy.subtil@gephi.org>
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gephi.desktop.preview.propertyeditors;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.gephi.preview.types.DependantColor;
import org.gephi.ui.components.JColorButton;

/**
 *
 * @author Mathieu Bastian
 */
public class DependantColorPanel extends javax.swing.JPanel implements ItemListener {

    /** Creates new form DependantColorPanel */
    public DependantColorPanel() {
        initComponents();
        colorButton.addPropertyChangeListener(JColorButton.EVENT_COLOR, new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent evt) {
                Color newColor = (Color) evt.getNewValue();
                propertyEditor.setValue(new DependantColor(newColor));
            }
        });

        parentRadio.addItemListener(this);
        customRadio.addItemListener(this);
    }

    public void itemStateChanged(ItemEvent e) {
        if (customRadio.isSelected()) {
            colorButton.setEnabled(true);
        } else {
            colorButton.setEnabled(false);
        }
        DependantColor.Mode selectedMode = null;
        if (parentRadio.isSelected()) {
            selectedMode = DependantColor.Mode.PARENT;
        } else if (customRadio.isSelected()) {
            selectedMode = DependantColor.Mode.CUSTOM;
        }
        propertyEditor.setValue(new DependantColor(selectedMode));
    }
    private DependantColorPropertyEditor propertyEditor;

    public void setup(DependantColorPropertyEditor propertyEditor) {
        this.propertyEditor = propertyEditor;
        DependantColor dependantColor = (DependantColor) propertyEditor.getValue();
        if (dependantColor.getMode().equals(DependantColor.Mode.CUSTOM)) {
            customRadio.setSelected(true);
            ((JColorButton) colorButton).setColor(dependantColor.getCustomColor());
        } else if (dependantColor.getMode().equals(DependantColor.Mode.PARENT)) {
            parentRadio.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        colorButton = new JColorButton(Color.BLACK);
        customRadio = new javax.swing.JRadioButton();
        parentRadio = new javax.swing.JRadioButton();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();

        buttonGroup1.add(customRadio);
        customRadio.setText(org.openide.util.NbBundle.getMessage(DependantColorPanel.class, "DependantColorPanel.customRadio.text")); // NOI18N

        buttonGroup1.add(parentRadio);
        parentRadio.setText(org.openide.util.NbBundle.getMessage(DependantColorPanel.class, "DependantColorPanel.parentRadio.text")); // NOI18N

        jXHeader1.setDescription(org.openide.util.NbBundle.getMessage(DependantColorPanel.class, "DependantColorPanel.jXHeader1.description")); // NOI18N
        jXHeader1.setTitle(org.openide.util.NbBundle.getMessage(DependantColorPanel.class, "DependantColorPanel.jXHeader1.title")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jXHeader1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(parentRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(customRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(colorButton)))
                .add(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jXHeader1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(parentRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(customRadio)
                    .add(colorButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton colorButton;
    private javax.swing.JRadioButton customRadio;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JRadioButton parentRadio;
    // End of variables declaration//GEN-END:variables
}
