/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RandomGraphPanel.java
 *
 * Created on 15 juin 2009, 20:41:16
 */
package org.gephi.ui.generator.standard;

import org.gephi.io.generator.standard.*;
import javax.swing.JPanel;
import org.gephi.io.generator.Generator;
import org.gephi.ui.generator.GeneratorUI;
import org.gephi.validation.BetweenZeroAndOneValidator;
import org.gephi.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Mathieu Bastian
 */
public class RandomGraphPanel extends javax.swing.JPanel {

    /** Creates new form RandomGraphPanel */
    public RandomGraphPanel() {
        initComponents();
    }

    public static ValidationPanel createValidationPanel(RandomGraphPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new RandomGraphPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        //Node field
        group.add(innerPanel.nodeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new PositiveNumberValidator());

        //Edge field
        group.add(innerPanel.edgeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new BetweenZeroAndOneValidator());

        return validationPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeLabel = new javax.swing.JLabel();
        edgeLabel = new javax.swing.JLabel();
        nodeField = new javax.swing.JTextField();
        edgeField = new javax.swing.JTextField();

        nodeLabel.setText(org.openide.util.NbBundle.getMessage(RandomGraphPanel.class, "RandomGraphPanel.nodeLabel.text")); // NOI18N

        edgeLabel.setText(org.openide.util.NbBundle.getMessage(RandomGraphPanel.class, "RandomGraphPanel.edgeLabel.text")); // NOI18N

        nodeField.setText(org.openide.util.NbBundle.getMessage(RandomGraphPanel.class, "RandomGraphPanel.nodeField.text")); // NOI18N

        edgeField.setText(org.openide.util.NbBundle.getMessage(RandomGraphPanel.class, "RandomGraphPanel.edgeField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nodeLabel)
                    .addComponent(edgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edgeField)
                    .addComponent(nodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edgeLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField edgeField;
    private javax.swing.JLabel edgeLabel;
    protected javax.swing.JTextField nodeField;
    private javax.swing.JLabel nodeLabel;
    // End of variables declaration//GEN-END:variables

    public static class RandomGraphUI implements GeneratorUI {

        private RandomGraphPanel panel;
        private RandomGraph randomGraph;

        public RandomGraphUI() {
            panel = new RandomGraphPanel();
        }

        public JPanel getPanel() {
            return RandomGraphPanel.createValidationPanel(panel);
        }

        public void setup(Generator generator) {
            this.randomGraph = (RandomGraph) generator;

            //Set UI
            panel.nodeField.setText(String.valueOf(randomGraph.getNumberOfNodes()));
            panel.edgeField.setText(String.valueOf(randomGraph.getWiringProbability()));
        }

        public void unsetup() {
            //Set params
            randomGraph.setNumberOfNodes(Integer.parseInt(panel.nodeField.getText()));
            randomGraph.setWiringProbability(Double.parseDouble(panel.edgeField.getText()));
        }
    }
}
