/*
Copyright 2008-2011 Gephi
Authors : Daniel Bernardes <daniel.bernardes@polytechnique.edu>
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gephi.ui.exporter.plugin;

import org.gephi.io.exporter.plugin.ExporterPajek;

/**
 *
 * @author Daniel Bernardes
 */
public class UIExporterPajekPanel extends javax.swing.JPanel {

    public UIExporterPajekPanel() {
        initComponents();
    }

    public void setup(ExporterPajek exporterPajek) {
        positionExportCheckbox.setSelected(exporterPajek.isExportPosition());
        edgeWeightCheckbox.setSelected(exporterPajek.isExportEdgeWeight());
    }

    public void unsetup(ExporterPajek exporterPajek) {
        exporterPajek.setExportPosition(positionExportCheckbox.isSelected());
        exporterPajek.setExportEdgeWeight(edgeWeightCheckbox.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelExport = new javax.swing.JLabel();
        positionExportCheckbox = new javax.swing.JCheckBox();
        edgeWeightCheckbox = new javax.swing.JCheckBox();


        labelExport.setText(org.openide.util.NbBundle.getMessage(UIExporterPajekPanel.class, "UIExporterPajekPanel.labelExport.text")); // NOI18N

        positionExportCheckbox.setText(org.openide.util.NbBundle.getMessage(UIExporterPajekPanel.class, "UIExporterPajekPanel.positionExportCheckbox.text")); // NOI18N

        edgeWeightCheckbox.setText(org.openide.util.NbBundle.getMessage(UIExporterPajekPanel.class, "UIExporterPajekPanel.edgeWeightCheckbox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExport)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edgeWeightCheckbox)
                                    .addComponent(positionExportCheckbox)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExport)
                    .addComponent(positionExportCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edgeWeightCheckbox))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox edgeWeightCheckbox;
    private javax.swing.JLabel labelExport;
    private javax.swing.JCheckBox positionExportCheckbox;
    // End of variables declaration//GEN-END:variables
}
