/*
 Copyright 2008-2010 Gephi
 Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
 Website : http://www.gephi.org

 This file is part of Gephi.

 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

 Copyright 2011 Gephi Consortium. All rights reserved.

 The contents of this file are subject to the terms of either the GNU
 General Public License Version 3 only ("GPL") or the Common
 Development and Distribution License("CDDL") (collectively, the
 "License"). You may not use this file except in compliance with the
 License. You can obtain a copy of the License at
 http://gephi.org/about/legal/license-notice/
 or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
 specific language governing permissions and limitations under the
 License.  When distributing the software, include this License Header
 Notice in each file and include the License files at
 /cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
 License Header, with the fields enclosed by brackets [] replaced by
 your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"

 If you wish your version of this file to be governed by only the CDDL
 or only the GPL Version 3, indicate your decision by adding
 "[Contributor] elects to include this software in this distribution
 under the [CDDL or GPL Version 3] license." If you do not indicate a
 single choice of license, a recipient has the option to distribute
 your version of this file under either the CDDL, the GPL Version 3 or
 to extend the choice of license to its licensees as provided above.
 However, if you add GPL Version 3 code and therefore, elected the GPL
 Version 3 license, then the option applies only if the new code is
 made subject to such option by the copyright holder.

 Contributor(s):

 Portions Copyrighted 2011 Gephi Consortium.
 */

package org.gephi.desktop.visualization.collapse;

import java.awt.Font;
import java.beans.PropertyChangeEvent;
import org.gephi.visualization.api.VisualisationModel;
import org.gephi.visualization.api.VisualizationController;
import org.gephi.visualization.api.VisualizationPropertyChangeListener;
import org.openide.util.Lookup;

/**
 * @author Mathieu Bastian
 */
public class NodeSettingsPanel extends javax.swing.JPanel implements VisualizationPropertyChangeListener {

    private final VisualizationController vizController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelScale;
    private javax.swing.JPanel scalePanel;
    private javax.swing.JSlider scaleSlider;
    private javax.swing.JCheckBox showNodesCheckbox;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form NodeSettingsPanel
     */
    public NodeSettingsPanel() {
        initComponents();

        vizController = Lookup.getDefault().lookup(VisualizationController.class);

        scaleSlider.addChangeListener(e -> {
            vizController.setNodeScale(scaleSlider.getValue() / 10f + 0.1f);
        });
    }

    public void setup(VisualisationModel model) {
        if (model == null) {
            setEnable(false);
            return;
        }
        refreshSharedConfig(model);
        setEnable(true);
        vizController.addPropertyChangeListener(this);
    }

    public void unsetup(VisualisationModel model) {
        vizController.removePropertyChangeListener(this);
    }

    @Override
    public void propertyChange(VisualisationModel model, PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("nodeScale")) {
            refreshSharedConfig(model);
        }
    }

    private void refreshSharedConfig(VisualisationModel vizModel) {
        if (scaleSlider.getValue() / 10f + 0.1f != vizModel.getNodeScale()) {
            scaleSlider.setValue((int) ((vizModel.getNodeScale() - 0.1f) * 10));
        }
    }

    private void setEnable(boolean enable) {
        scaleSlider.setEnabled(enable && showNodesCheckbox.isSelected());
        labelScale.setEnabled(enable && showNodesCheckbox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        showNodesCheckbox = new javax.swing.JCheckBox();
        scalePanel = new javax.swing.JPanel();
        labelScale = new javax.swing.JLabel();
        scaleSlider = new javax.swing.JSlider();

        showNodesCheckbox.setFont(new java.awt.Font("Tahoma", Font.BOLD, 11)); // NOI18N
        showNodesCheckbox.setSelected(true);
        showNodesCheckbox.setText(org.openide.util.NbBundle.getMessage(NodeSettingsPanel.class,
            "NodeSettingsPanel.showNodesCheckbox.text")); // NOI18N
        showNodesCheckbox.setEnabled(false);

        scalePanel.setOpaque(false);
        scalePanel.setLayout(new java.awt.GridBagLayout());

        labelScale.setText(org.openide.util.NbBundle.getMessage(NodeSettingsPanel.class,
            "NodeSettingsPanel.labelScale.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 2, 0);
        scalePanel.add(labelScale, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        scalePanel.add(scaleSlider, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(scalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 205,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(showNodesCheckbox))
                    .addContainerGap(520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showNodesCheckbox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents
}
