/*
Copyright 2008 WebAtlas
Authors : Mathieu Bastian, Mathieu Jacomy, Julian Bilcke
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gephi.ui.tools;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import org.gephi.ui.components.gradientslider.GradientSlider;

/**
 *
 * @author Mathieu Bastian
 */
public class HeatMapPanel extends javax.swing.JPanel {

    private GradientSlider slider;
    private JCheckBox dontPaintUnreachableCheckbox;

    /** Creates new form HeatMapPanel */
    public HeatMapPanel(Color[] gradientColors, float[] gradientPositions, boolean dontPaintUnreachable) {
        initComponents();

        //Slider
        slider = new GradientSlider(GradientSlider.HORIZONTAL, gradientPositions, gradientColors);
        slider.putClientProperty("GradientSlider.includeOpacity", "false");
        gradientPanel.add(slider);

        //Checkbox
        dontPaintUnreachableCheckbox = new JCheckBox();
        dontPaintUnreachableCheckbox.setSelected(dontPaintUnreachable);
        dontPaintUnreachableCheckbox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        dontPaintUnreachableCheckbox.setText(org.openide.util.NbBundle.getMessage(HeatMapPanel.class, "HeatMapPanel.dontPaintUnreachableCheckbox.text")); // NOI18N
        dontPaintUnreachableCheckbox.setPreferredSize(new java.awt.Dimension(139, 28));
        gradientPanel.add(dontPaintUnreachableCheckbox);
        initEvents();
    }

    public void setStatus(String status) {
        statusLabel.setText(status);
    }

    public Color[] getGradientColors() {
        return (Color[]) slider.getColors();
    }

    public float[] getGradientPositions() {
        return slider.getThumbPositions();
    }

    public boolean isDontPaintUnreachable() {
        return dontPaintUnreachableCheckbox.isSelected();
    }

    private void initEvents() {
        modeComboBox.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (modeComboBox.getSelectedIndex() == 0) {
                    //Gradient
                    gradientPanel.setVisible(true);
                    palettePanel.setVisible(false);
                } else {
                    //Palette
                    gradientPanel.setVisible(false);
                    palettePanel.setVisible(true);
                }
            }
        });
        palettePanel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        labelMode = new javax.swing.JLabel();
        modeComboBox = new javax.swing.JComboBox();
        gradientPanel = new javax.swing.JPanel();
        labelGradient = new javax.swing.JLabel();
        palettePanel = new javax.swing.JPanel();
        labelPalette = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(654, 28));

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 10));
        statusLabel.setText(org.openide.util.NbBundle.getMessage(HeatMapPanel.class, "HeatMapPanel.statusLabel.text")); // NOI18N

        labelMode.setFont(new java.awt.Font("Tahoma", 0, 10));
        labelMode.setText(org.openide.util.NbBundle.getMessage(HeatMapPanel.class, "HeatMapPanel.labelMode.text")); // NOI18N

        modeComboBox.setFont(new java.awt.Font("Tahoma", 0, 10));
        modeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gradient", "Palette" }));

        gradientPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        labelGradient.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelGradient.setText(org.openide.util.NbBundle.getMessage(HeatMapPanel.class, "HeatMapPanel.labelGradient.text")); // NOI18N
        labelGradient.setPreferredSize(new java.awt.Dimension(45, 28));
        gradientPanel.add(labelGradient);

        palettePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        labelPalette.setFont(new java.awt.Font("Tahoma", 0, 10));
        labelPalette.setText(org.openide.util.NbBundle.getMessage(HeatMapPanel.class, "HeatMapPanel.labelPalette.text")); // NOI18N
        labelPalette.setPreferredSize(new java.awt.Dimension(45, 28));
        palettePanel.add(labelPalette);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gradientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palettePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(modeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(palettePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(gradientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gradientPanel;
    private javax.swing.JLabel labelGradient;
    private javax.swing.JLabel labelMode;
    private javax.swing.JLabel labelPalette;
    private javax.swing.JComboBox modeComboBox;
    private javax.swing.JPanel palettePanel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
