/*
 Copyright 2008-2010 Gephi
 Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
 Website : http://www.gephi.org

 This file is part of Gephi.

 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

 Copyright 2011 Gephi Consortium. All rights reserved.

 The contents of this file are subject to the terms of either the GNU
 General Public License Version 3 only ("GPL") or the Common
 Development and Distribution License("CDDL") (collectively, the
 "License"). You may not use this file except in compliance with the
 License. You can obtain a copy of the License at
 http://gephi.org/about/legal/license-notice/
 or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
 specific language governing permissions and limitations under the
 License.  When distributing the software, include this License Header
 Notice in each file and include the License files at
 /cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
 License Header, with the fields enclosed by brackets [] replaced by
 your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"

 If you wish your version of this file to be governed by only the CDDL
 or only the GPL Version 3, indicate your decision by adding
 "[Contributor] elects to include this software in this distribution
 under the [CDDL or GPL Version 3] license." If you do not indicate a
 single choice of license, a recipient has the option to distribute
 your version of this file under either the CDDL, the GPL Version 3 or
 to extend the choice of license to its licensees as provided above.
 However, if you add GPL Version 3 code and therefore, elected the GPL
 Version 3 license, then the option applies only if the new code is
 made subject to such option by the copyright holder.

 Contributor(s):

 Portions Copyrighted 2011 Gephi Consortium.
 */

package org.gephi.desktop.layout;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import org.openide.util.ImageUtilities;

public class TransformationPanel extends javax.swing.JPanel implements PropertyChangeListener {

    public TransformationPanel(){
        initComponents();
    }

  private final ImageIcon iconMirrorY = ImageUtilities.loadImageIcon(
        "DesktopTransform/drawing-geometry-symmetry-direction-interaction-move-svgrepo-com.svg", false);
    private final ImageIcon iconMirrorX = ImageUtilities.loadImageIcon(
        "DesktopTransform/measuring-symmetry-tool-direction-interaction-move-svgrepo-com.svg", false);

    private final ImageIcon iconRotateRight1deg =
        ImageUtilities.loadImageIcon("DesktopTransform/rotate-right-svgrepo-com_1deg.svg", false);
    private final ImageIcon iconRotateLeft1deg =
        ImageUtilities.loadImageIcon("DesktopTransform/rotate-left-svgrepo-com_1deg.svg", false);

    private final ImageIcon iconRotateRight45deg =
        ImageUtilities.loadImageIcon("DesktopTransform/rotate-right-svgrepo-com_45deg.svg", false);
    private final ImageIcon iconRotateLeft45deg =
        ImageUtilities.loadImageIcon("DesktopTransform/rotate-left-svgrepo-com_45deg.svg", false);

    private final ImageIcon iconScaleExpand =
        ImageUtilities.loadImageIcon("DesktopTransform/scale-expand-svgrepo-com.svg", false);
    private final ImageIcon iconScaleReduce =
        ImageUtilities.loadImageIcon("DesktopTransform/scale-reduce-svgrepo-com.svg", false);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExpand;
    private javax.swing.JButton buttonMirrorX;
    private javax.swing.JButton buttonMirrorY;
    private javax.swing.JButton buttonReduce;
    private javax.swing.JButton buttonRotateLeft1deg;
    private javax.swing.JButton buttonRotateLeft45deg;
    private javax.swing.JButton buttonRotateRight1deg;
    private javax.swing.JButton buttonRotateRight45deg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMirrorY = new javax.swing.JButton(this.iconMirrorY);
        buttonMirrorX = new javax.swing.JButton(this.iconMirrorX);
        jSeparator1 = new javax.swing.JSeparator();
        buttonRotateLeft45deg = new javax.swing.JButton(this.iconRotateLeft45deg);
        buttonRotateLeft1deg = new javax.swing.JButton(this.iconRotateLeft1deg);
        buttonRotateRight1deg = new javax.swing.JButton(this.iconRotateRight1deg);
        buttonRotateRight45deg = new javax.swing.JButton(this.iconRotateRight45deg);
        jSeparator2 = new javax.swing.JSeparator();
        buttonExpand = new javax.swing.JButton(this.iconScaleExpand);
        buttonReduce = new javax.swing.JButton(this.iconScaleReduce);

        buttonMirrorY.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonMirrorY.text")); // NOI18N
        add(buttonMirrorY);

        buttonMirrorX.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonMirrorX.text")); // NOI18N
        add(buttonMirrorX);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(8, 16));
        jSeparator1.setPreferredSize(new java.awt.Dimension(8, 16));
        add(jSeparator1);

        buttonRotateLeft45deg.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonRotateLeft45deg.text")); // NOI18N
        add(buttonRotateLeft45deg);

        buttonRotateLeft1deg.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonRotateLeft1deg.text")); // NOI18N
        add(buttonRotateLeft1deg);

        buttonRotateRight1deg.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonRotateRight1deg.text")); // NOI18N
        add(buttonRotateRight1deg);

        buttonRotateRight45deg.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonRotateRight45deg.text")); // NOI18N
        add(buttonRotateRight45deg);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(8, 16));
        jSeparator2.setPreferredSize(new java.awt.Dimension(8, 16));
        add(jSeparator2);

        buttonExpand.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonExpand.text")); // NOI18N
        add(buttonExpand);

        buttonReduce.setText(org.openide.util.NbBundle.getMessage(TransformationPanel.class, "TransformationPanel.buttonReduce.text")); // NOI18N
        add(buttonReduce);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
