/*
 Copyright 2008-2010 Gephi
 Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
 Website : http://www.gephi.org

 This file is part of Gephi.

 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

 Copyright 2011 Gephi Consortium. All rights reserved.

 The contents of this file are subject to the terms of either the GNU
 General Public License Version 3 only ("GPL") or the Common
 Development and Distribution License("CDDL") (collectively, the
 "License"). You may not use this file except in compliance with the
 License. You can obtain a copy of the License at
 http://gephi.org/about/legal/license-notice/
 or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
 specific language governing permissions and limitations under the
 License.  When distributing the software, include this License Header
 Notice in each file and include the License files at
 /cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
 License Header, with the fields enclosed by brackets [] replaced by
 your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"

 If you wish your version of this file to be governed by only the CDDL
 or only the GPL Version 3, indicate your decision by adding
 "[Contributor] elects to include this software in this distribution
 under the [CDDL or GPL Version 3] license." If you do not indicate a
 single choice of license, a recipient has the option to distribute
 your version of this file under either the CDDL, the GPL Version 3 or
 to extend the choice of license to its licensees as provided above.
 However, if you add GPL Version 3 code and therefore, elected the GPL
 Version 3 license, then the option applies only if the new code is
 made subject to such option by the copyright holder.

 Contributor(s):

 Portions Copyrighted 2011 Gephi Consortium.
 */

package org.gephi.desktop.layout;

import javax.swing.ImageIcon;
import org.openide.util.ImageUtilities;


public class TransformationPanel extends javax.swing.JPanel {
    private final TransformationUIController transformationUIController;

    public TransformationPanel() {
        initComponents();
        transformationUIController = new TransformationUIController();
    }

    private final ImageIcon iconMirrorY = ImageUtilities.loadImageIcon(
        "DesktopLayout/transformations/mirror_yaxis.svg", false);
    private final ImageIcon iconMirrorX = ImageUtilities.loadImageIcon(
        "DesktopLayout/transformations/mirror_xaxis.svg", false);

    private final ImageIcon iconRotateRight1deg =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/rotate_right_1deg.svg", false);
    private final ImageIcon iconRotateLeft1deg =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/rotate_left_1deg.svg", false);

    private final ImageIcon iconRotateRight45deg =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/rotate_right_45deg.svg", false);
    private final ImageIcon iconRotateLeft45deg =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/rotate_left_45deg.svg", false);

    private final ImageIcon iconScaleExpand =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/scale_expand.svg", false);
    private final ImageIcon iconScaleReduce =
        ImageUtilities.loadImageIcon("DesktopLayout/transformations/scale_reduce.svg", false);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExpand;
    private javax.swing.JButton buttonMirrorX;
    private javax.swing.JButton buttonMirrorY;
    private javax.swing.JButton buttonReduce;
    private javax.swing.JButton buttonRotateLeft1deg;
    private javax.swing.JButton buttonRotateLeft45deg;
    private javax.swing.JButton buttonRotateRight1deg;
    private javax.swing.JButton buttonRotateRight45deg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMirrorY = new javax.swing.JButton(this.iconMirrorY);
        buttonMirrorX = new javax.swing.JButton(this.iconMirrorX);
        jSeparator1 = new javax.swing.JSeparator();
        buttonRotateLeft45deg = new javax.swing.JButton(this.iconRotateLeft45deg);
        buttonRotateLeft1deg = new javax.swing.JButton(this.iconRotateLeft1deg);
        buttonRotateRight1deg = new javax.swing.JButton(this.iconRotateRight1deg);
        buttonRotateRight45deg = new javax.swing.JButton(this.iconRotateRight45deg);
        jSeparator2 = new javax.swing.JSeparator();
        buttonExpand = new javax.swing.JButton(this.iconScaleExpand);
        buttonReduce = new javax.swing.JButton(this.iconScaleReduce);

        buttonMirrorY.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonMirrorY.toolTipText")); // NOI18N
        buttonMirrorY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMirrorYActionPerformed(evt);
            }
        });
        add(buttonMirrorY);

        buttonMirrorX.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonMirrorX.toolTipText")); // NOI18N
        buttonMirrorX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMirrorXActionPerformed(evt);
            }
        });
        add(buttonMirrorX);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(8, 16));
        jSeparator1.setPreferredSize(new java.awt.Dimension(8, 16));
        add(jSeparator1);

        buttonRotateLeft45deg.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonRotateLeft45deg.toolTipText")); // NOI18N
        buttonRotateLeft45deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotateLeft45degActionPerformed(evt);
            }
        });
        add(buttonRotateLeft45deg);

        buttonRotateLeft1deg.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonRotateLeft1deg.toolTipText")); // NOI18N
        buttonRotateLeft1deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotateLeft1degActionPerformed(evt);
            }
        });
        add(buttonRotateLeft1deg);

        buttonRotateRight1deg.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonRotateRight1deg.toolTipText")); // NOI18N
        buttonRotateRight1deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotateRight1degActionPerformed(evt);
            }
        });
        add(buttonRotateRight1deg);

        buttonRotateRight45deg.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonRotateRight45deg.toolTipText")); // NOI18N
        buttonRotateRight45deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotateRight45degActionPerformed(evt);
            }
        });
        add(buttonRotateRight45deg);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(8, 16));
        jSeparator2.setPreferredSize(new java.awt.Dimension(8, 16));
        add(jSeparator2);

        buttonExpand.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonExpand.toolTipText")); // NOI18N
        buttonExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExpandActionPerformed(evt);
            }
        });
        add(buttonExpand);

        buttonReduce.setToolTipText(org.openide.util.NbBundle.getMessage(TransformationPanel.class,
            "TransformationPanel.buttonReduce.toolTipText")); // NOI18N
        buttonReduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReduceActionPerformed(evt);
            }
        });
        add(buttonReduce);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMirrorYActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMirrorYActionPerformed
        transformationUIController.mirrorYAxis();
    }//GEN-LAST:event_buttonMirrorYActionPerformed

    private void buttonMirrorXActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMirrorXActionPerformed
        transformationUIController.mirrorXAxis();
    }//GEN-LAST:event_buttonMirrorXActionPerformed

    private void buttonRotateLeft45degActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotateLeft45degActionPerformed
        transformationUIController.rotateLeft45Deg();
    }//GEN-LAST:event_buttonRotateLeft45degActionPerformed

    private void buttonRotateLeft1degActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotateLeft1degActionPerformed
        transformationUIController.rotateLeft1Deg();
    }//GEN-LAST:event_buttonRotateLeft1degActionPerformed

    private void buttonRotateRight1degActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotateRight1degActionPerformed
        transformationUIController.rotateRight1Deg();
    }//GEN-LAST:event_buttonRotateRight1degActionPerformed

    private void buttonRotateRight45degActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotateRight45degActionPerformed
        transformationUIController.rotateRight45Deg();
    }//GEN-LAST:event_buttonRotateRight45degActionPerformed

    private void buttonExpandActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExpandActionPerformed
        transformationUIController.expand();
    }//GEN-LAST:event_buttonExpandActionPerformed

    private void buttonReduceActionPerformed(
        java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReduceActionPerformed
        transformationUIController.reduce();
    }//GEN-LAST:event_buttonReduceActionPerformed

}
