/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.gephi.data.laboratory;

import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.explorer.view.NodeTableModel;
import org.openide.explorer.view.TreeTableView;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class DataExplorerTopComponent extends TopComponent {

    private static DataExplorerTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "DataExplorerTopComponent";

    //TableModel
    private NodeTableModel nodeModel;
    private NodeTableModel edgeModel;

    private DataExplorerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(DataExplorerTopComponent.class, "CTL_DataExplorerTopComponent"));
        setToolTipText(NbBundle.getMessage(DataExplorerTopComponent.class, "HINT_DataExplorerTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    private void initNodesView()
    {

        nodeModel = new NodeTableModel();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        nodesPanel = new javax.swing.JPanel();
        nodesView = new TreeTableView();
        edgesPanel = new javax.swing.JPanel();
        edgesView = new TreeTableView();

        setLayout(new java.awt.BorderLayout());

        nodesPanel.setLayout(new java.awt.BorderLayout());
        nodesPanel.add(nodesView, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(DataExplorerTopComponent.class, "DataExplorerTopComponent.nodesPanel.TabConstraints.tabTitle"), nodesPanel); // NOI18N

        edgesPanel.setLayout(new java.awt.BorderLayout());
        edgesPanel.add(edgesView, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(DataExplorerTopComponent.class, "DataExplorerTopComponent.edgesPanel.TabConstraints.tabTitle"), edgesPanel); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel edgesPanel;
    private javax.swing.JScrollPane edgesView;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel nodesPanel;
    private javax.swing.JScrollPane nodesView;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized DataExplorerTopComponent getDefault() {
        if (instance == null) {
            instance = new DataExplorerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the DataExplorerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized DataExplorerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(DataExplorerTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof DataExplorerTopComponent) {
            return (DataExplorerTopComponent) win;
        }
        Logger.getLogger(DataExplorerTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return DataExplorerTopComponent.getDefault();
        }
    }
}
